//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_COCINA
    {
        public int ID_BITACORA_COCINA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<int> ID_BODEGA_GENERAL { get; set; }
    
        public virtual INVENTARIO_BODEGA_GENERAL INVENTARIO_BODEGA_GENERAL { get; set; }
    }
}
