//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_DATOS_ADICIONALES
    {
        public int ID_CLIENTE_DATO_ADICIONAL { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
