//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COBRO()
        {
            this.COBRO_DETALLE = new HashSet<COBRO_DETALLE>();
        }
    
        public int ID_COBRO { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<int> ID_CORTE { get; set; }
    
        public virtual CORTE CORTE { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COBRO_DETALLE> COBRO_DETALLE { get; set; }
    }
}
