//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DETALLE
    {
        public int SERIE { get; set; }
        public int NO_FACTURA { get; set; }
        public string RESOLUCION { get; set; }
        public int ID_FACTURA_ENCABEZADO { get; set; }
        public Nullable<int> NO_DETALLE { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> SUBTOTAL_DETALLE { get; set; }
        public string CONCEPTO { get; set; }
        public int ID_FACTURA_DETALLE { get; set; }
    
        public virtual FACTURA_ENCABEZADO FACTURA_ENCABEZADO { get; set; }
    }
}
