//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_COCINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO_COCINA()
        {
            this.MENU_DETALLE = new HashSet<MENU_DETALLE>();
            this.MENU_DETALLE1 = new HashSet<MENU_DETALLE>();
            this.MENU_DETALLE2 = new HashSet<MENU_DETALLE>();
        }
    
        public int ID_INVENTARIO_COCINA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CANTIDAD_NETA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> CANTIDAD_CONVERSION { get; set; }
        public Nullable<int> ID_UNIDAD_MEDIDA { get; set; }
        public Nullable<int> ID_BODEGA_GENERAL { get; set; }
    
        public virtual INVENTARIO_BODEGA_GENERAL INVENTARIO_BODEGA_GENERAL { get; set; }
        public virtual INVENTARIO_BODEGA_GENERAL INVENTARIO_BODEGA_GENERAL1 { get; set; }
        public virtual INVENTARIO_BODEGA_GENERAL INVENTARIO_BODEGA_GENERAL2 { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA1 { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_DETALLE> MENU_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_DETALLE> MENU_DETALLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_DETALLE> MENU_DETALLE2 { get; set; }
    }
}
