//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_DETALLE
    {
        public int ID_MENU_DETALLE { get; set; }
        public Nullable<int> ID_MENU { get; set; }
        public Nullable<int> ID_INVENTARIO_COCINA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual INVENTARIO_COCINA INVENTARIO_COCINA { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
