//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_MESA
    {
        public int ID_PAGO_MESA { get; set; }
        public int ID_MESA { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public int ID_PEDIDO { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
