//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_DETALLE
    {
        public int ID_DETALLE_PEDIDO { get; set; }
        public int ID_PEDIDO { get; set; }
        public int ID_MENU { get; set; }
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
