//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO_PANTALLA
    {
        public int ID_PERMISO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<int> ID_PANTALLA { get; set; }
        public string USUARIO { get; set; }
    
        public virtual PANTALLA PANTALLA { get; set; }
        public virtual PANTALLA PANTALLA1 { get; set; }
        public virtual PANTALLA PANTALLA2 { get; set; }
        public virtual ROL ROL { get; set; }
        public virtual ROL ROL1 { get; set; }
        public virtual ROL ROL2 { get; set; }
    }
}
