//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geminis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALES
    {
        public int ID_VALE { get; set; }
        public int ID_EMPLEADO { get; set; }
        public Nullable<decimal> TOTAL_VALE { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string ESTADO { get; set; }
        public string CREADO_POR { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
